### ISSUE TITLE
Active Directory password change

### ISSUE THREAD

**Issue by alexwhitman** [mcavage/node-ldapjs#92]
I'm trying to write a script which will allow users to change their own passwords on Active Directory.  After a successful bind as the user with their 'old' password, I'm using:

``` javascript
client.modify(userDN, [
    new ldap.Change({
        operation: 'delete',
        modification: {
            unicodePwd: encodePassword(oldPassword)
        }
    }),
    new ldap.Change({
        operation: 'add',
        modification: {
            unicodePwd: encodePassword(newPassword)
        }
    })
], function(err) {
    if (err) {
        console.log(err.dn);
        console.log(err.code);
        console.log(err.name);
        console.log(err.message);
        client.unbind();
    }
    else {
        console.log('Password changed!');
    }
});
```

Where `encodePassword` is defined as 

``` javascript
function encodePassword(password) {
    var newPassword = '';
    password = '"' + password + '"';
    for (var i = 0; i < password.length; i++) {
        newPassword += password[i] + "\000";
    }
    return new Buffer(newPassword).toString('base64');
}
```

which was taken from http://www.cs.bham.ac.uk/~smp/resources/ad-passwds/

The PHP script + ldapmodify works fine but the Node.js script gives a ConstraintViolationError with the message

```
0000216C: AtrErr: DSID-03190EB0, #1:
    0: 0000216C: DSID-03190EB0, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)
```

The new password meets the constraints applied by the server (complexity etc) so I'm not sure what's going wrong.  As the password change can only be done over ldaps I can't provide a Wireshark capture and I'm out of ideas.  Any suggestions?

**Comment by vajanishant** [comment]
I'm unable to change the user password using ldapjs.
 
Can someone please help me with this error?
I didn't find anything and tried every possible thing like replace, add, delete, with SSL, without SSL 

**For SSL connection I've used this code:**
await ldap.createClient({
			url: `ldap://${host}`,
			tlsOptions: {
				ca: [
					fs.readFileSync('filename.pem'),
				]
			}
		});

**I'm using this function to pass password:**
encodePassword(password) {
		return Buffer.from('"' + password + '"', 'utf16le').toString('base64');
	}

**This is my change object:**
[
			new ldap.Change({
				operation: 'delete',
				modification: {
					unicodePwd: this.encodePassword('Admin@123')
				}
			}),
			new ldap.Change({
				operation: 'add',
				modification: {					
					unicodePwd: this.encodePassword('Changed@123')					
				}
			})
		]

Getting  this error:

**UnwillingToPerformError
00002077: SvcErr: DSID-03190EBE, problem 5003 (WILL_NOT_PERFORM), data 0**

**Comment by PhilWaldmann** [comment]
If you connect to an ActiveDirectory, you need to connect via **ldaps** (port 636).
The format of the password is also important. Here is some [working code](https://github.com/PhilWaldmann/openrecord/blob/8ddb9af2d020422fea68f55b7b43527d01710d62/lib/stores/activedirectory/schema/user.js#L102) to transform the password string to the `unicodePwd`.
I'm not sure if a `delete` operation is allowed for the `unicodePwd` field, try `replace` instead

**Comment by vajanishant** [comment]
@PhilWaldmann 
I'm able to change displayName using replace so I have successfully created a connection with my active directory.

I was trying to change the unicodePwd variable from an active directory server.
Steps I've followed:

- Login to my active directory server's VM using the admin user.
- Go to the user and group management panel.
- Open any user's properties.
- Go to Attribute Editor tab (if you don't find that tab then click on view drop-down located in the title bar and enable Advance Features. )
- Now scroll up to unicodePwd attribute and check whether it's filled or not (In my case it was not set)
- Try to set that field and save the setting.

When I am trying to save the configuration it throws me an error.

**Operation Failed. Error code: 0x1f
A device attached to the system is not functioning.

0000001F: SvcErr: DSID-031A1262, problem 5003 (WILL_NOT_PERFORM), data 0**

So I am unable to change or set that attribute's value from the server itself maybe that's why I am unable to change that attribute's value from code also.

Please help with this.

Thank you.

**Comment by PhilWaldmann** [comment]
Did you read the [following](https://ldapwiki.com/wiki/UnicodePwd)?
You can't read the `unicodePwd` attribute. That's probably the reason why you wont find ich in the Attributes Editor.
However, in order to sehr the passwort your AD needs to be configured properly.
The Section "Process for a UnicodePwd Change" describes the `delete` + `add` vs `replace` operations in detail. So ignore my last comment about `delete`.

I was working on an administration tool for ActiveDirectory and OpenLDAP Servers a few years ago and the main problems were the proper AD configuration and the `unicodePwd` format. The AD is sometimes a real pain in the a** ;)
